version: "3.9"

services:
  app:
    image: my-app:v2
    ports:
      - "3000:3000"
    links:
      - monguito
  monguito:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nath
      - MONGO_INITDB_ROOT_PASSWORD=12345678
